index:
   path: /
   controller: App\Controller\DefaultController::index

create:
   path: /register/create
   controller: App\Controller\RegisterController::create

register:
   path: /register
   controller: App\Controller\RegisterController::index

